name: Docker Image CI - R_gdal_dev
on:
  workflow_dispatch: null
  schedule:
    - cron: '0 0,17 * * *'
  push:
    paths: ['dockerfiles/R_gdal_dev.Dockerfile', '.github/workflows/docker-R_gdal_dev.yml']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mdsumner/gdal-builds'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (R_gdal_dev) Docker image
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker build -f dockerfiles/R_gdal_dev.Dockerfile . --tag ghcr.io/mdsumner/gdal-builds:R_gdal_dev
      - name: Publish (R_gdal_dev)
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker push ghcr.io/mdsumner/gdal-builds:R_gdal_dev

