name: Docker Image CI - gdal-dev_ubuntu-small
on:
  workflow_dispatch: null
  push:
    paths: ['small/Dockerfile', '.github/workflows/docker-gdal-dev_ubuntu-small.yml', 'scripts/install_cmake_version_proj.sh']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mdsumner/gdal-builds'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (gdal-dev_ubuntu-small) Docker image
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker build -f small/Dockerfile . --tag ghcr.io/mdsumner/gdal-builds:gdal-dev_ubuntu-small
      - name: Publish (gdal-dev_ubuntu-small)
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker push ghcr.io/mdsumner/gdal-builds:gdal-dev_ubuntu-small

