name: Docker Image CI - gdal_dev
on:
  workflow_dispatch: null
  push:
    paths: ['dockerfiles/gdal_dev.Dockerfile', '.github/workflows/docker-gdal_dev.yml']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mdsumner/gdal-builds'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (gdal_dev) Docker image
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker build -f dockerfiles/gdal_dev.Dockerfile . --tag ghcr.io/mdsumner/gdal-builds:gdal_dev
      - name: Publish (gdal_dev)
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker push ghcr.io/mdsumner/gdal-builds:gdal_dev

