name: Docker Image CI - gdal-dev
on:
  workflow_dispatch: null
  schedule:
    - cron: '0 0,16 * * *'
  push:
    paths: ['dockerfiles/gdal-dev.Dockerfile', '.github/workflows/docker-gdal-dev.yml', 'scripts/install_cmake_version_proj.sh']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mdsumner/gdal-builds'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (gdal-dev) Docker image
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker build -f dockerfiles/gdal-dev.Dockerfile . --tag ghcr.io/mdsumner/gdal-builds:gdal-dev
      - name: Publish (gdal-dev)
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker push ghcr.io/mdsumner/gdal-builds:gdal-dev

