name: Docker Image CI - rocker-gdal-dev
on:
  workflow_dispatch: null
  schedule:
    - cron: '0 8 * * *'
  push:
    paths: ['dockerfiles/rocker-gdal-dev.Dockerfile', '.github/workflows/docker-rocker-gdal-dev.yml', 'scripts/install_gdal-dev.sh', 'scripts/install_tidyverse.sh']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mdsumner/gdal-builds'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (rocker-gdal-dev) Docker image
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker build -f dockerfiles/rocker-gdal-dev.Dockerfile . --tag ghcr.io/mdsumner/gdal-builds:rocker-gdal-dev
      - name: Publish (rocker-gdal-dev)
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker push ghcr.io/mdsumner/gdal-builds:rocker-gdal-dev

