name: Docker Image CI - RStudio_gdal_dev_python
on:
  workflow_dispatch: null
  schedule:
    - cron: '0 0,18 * * *'
  push:
    paths: ['dockerfiles/RStudio_gdal_dev_python.Dockerfile', '.github/workflows/docker-RStudio_gdal_dev_python.yml']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mdsumner/gdal-builds'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (RStudio_gdal_dev_python) Docker image
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker build -f dockerfiles/RStudio_gdal_dev_python.Dockerfile . --tag ghcr.io/mdsumner/gdal-builds:RStudio_gdal_dev_python
      - name: Publish (RStudio_gdal_dev_python)
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker push ghcr.io/mdsumner/gdal-builds:RStudio_gdal_dev_python

