name: Docker Image CI - gdal-dev_ubuntu-full
on:
  workflow_dispatch: null
  push:
    paths: ['full/Dockerfile', '.github/workflows/docker-gdal-dev_ubuntu-full.yml']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'mdsumner/gdal-builds'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the (gdal-dev_ubuntu-full) Docker image
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker build -f full/Dockerfile . --tag ghcr.io/mdsumner/gdal-builds:gdal-dev_ubuntu-full
      - name: Publish (gdal-dev_ubuntu-full)
        if: github.repository == 'mdsumner/gdal-builds'
        run: docker push ghcr.io/mdsumner/gdal-builds:gdal-dev_ubuntu-full

